theme = "custom"

[keys.normal]
C-y = ":sh tmux new-window -n fx '~/.config/helix/yazi-picker-tmux.sh open'"
C-u = ":sh zellij run -n Yazi -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker-zellij.sh open"
# C-y = ":sh zellij run -d left -- bash ~/.config/helix/yazi-picker.sh"

# [keys.normal.C-y]
# y = ":sh zellij run -n Yazi -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker-zellij.sh open"
# v = ":sh zellij run -n Yazi -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker-zellij.sh vsplit"
# h = ":sh zellij run -n Yazi -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker-zellij.sh hsplit"
